"""Add order and payment events

Revision ID: 0528f5177f94
Revises: 3d110a8142bf
Create Date: 2026-08-25 09:52:38.264160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0528f5177f94'
down_revision: Union[str, Sequence[str], None] = '3d110a8142bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_payment_events_payment_id_payments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_events')),
    sa.UniqueConstraint('provider_event_id', name=op.f('uq_payment_events_provider_event_id'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('shipping_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('shipping_address_snapshot', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('billing_address_snapshot', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled', 'payment_failed', 'refund_pending', 'refunded', 'return_requested', 'return_approved', name='order_status'),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_payment_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('provider_event_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('refunded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('metadata_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('metadata_json')
        batch_op.drop_column('refunded_at')
        batch_op.drop_column('refund_amount')
        batch_op.drop_column('provider_event_id')
        batch_op.drop_column('provider_payment_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled', 'payment_failed', 'refund_pending', 'refunded', 'return_requested', 'return_approved', name='order_status'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('billing_address_snapshot')
        batch_op.drop_column('shipping_address_snapshot')
        batch_op.drop_column('shipping_amount')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('discount_amount')

    op.drop_table('payment_events')
    # ### end Alembic commands ###
