"""updated address and user models for timestamps

Revision ID: 136d4899abe2
Revises: b9f8c01d8585
Create Date: 2025-11-07 11:21:45.755702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136d4899abe2'
down_revision: Union[str, Sequence[str], None] = 'b9f8c01d8585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('addresses', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'updated_at')
    op.drop_column('addresses', 'created_at')
    # ### end Alembic commands ###
