"""Initial schema baseline

Revision ID: 163fcf903f0c
Revises:
Create Date: 2026-09-11 00:00:00.000000

This migration did not exist until now. The chain's original first migration,
e71d0e330657 ("Add AuditLog and Performance Indexes"), has down_revision=None
but its upgrade() only adds an audit_logs table with a foreign key to
`users` — it assumes the base schema (users, products, orders, carts, etc.)
already exists. That assumption held for every environment that was set up
before Alembic was adopted (the schema was created some other way, then
`alembic stamp head` was run against it), but it means `alembic upgrade head`
has never actually worked against a genuinely empty database.

This migration creates exactly that missing base schema — the state of the
database immediately before e71d0e330657 was ever applied — and is inserted
as the new root of the chain (e71d0e330657.down_revision now points here
instead of to None). It was generated by reconstructing that state directly:
building the full current schema from today's SQLAlchemy models, running
every existing migration's downgrade() against it in reverse (which by
definition undoes every incremental change those migrations made), and
reflecting whatever schema remained.

Existing environments are unaffected: alembic only walks forward from a
database's *current* stamped revision, and every environment that already
has e71d0e330657 or later stamped is already past this point in the chain,
so this migration is never executed for them. Only a genuinely fresh
database — where `alembic upgrade head` previously failed outright — now
has a path from nothing to head.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '163fcf903f0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('brands',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('brands_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('logo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_brands'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_brands_id', 'brands', ['id'], unique=False, postgresql_include=[])
    op.create_index('ix_brands_name', 'brands', ['name'], unique=True, postgresql_include=[])
    op.create_index('ix_brands_slug', 'brands', ['slug'], unique=True, postgresql_include=[])
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('categories_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name='fk_categories_parent_id_categories'),
    sa.PrimaryKeyConstraint('id', name='pk_categories'),
    sa.UniqueConstraint('name', name='uq_categories_name', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('slug', name='uq_categories_slug', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('coupons',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('coupons_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('discount_type', postgresql.ENUM('percentage', 'fixed', name='discount_types'), autoincrement=False, nullable=False),
    sa.Column('discount_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('min_order_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('usage_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('used_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valid_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('valid_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_coupons'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_coupons_code', 'coupons', ['code'], unique=True, postgresql_include=[])
    op.create_table('outbox_events',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('outbox_events_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='outbox_status'), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_outbox_events')
    )
    op.create_index('ix_outbox_events_status_created', 'outbox_events', ['status', 'created_at'], unique=False, postgresql_include=[])
    op.create_index('ix_outbox_events_topic', 'outbox_events', ['topic'], unique=False, postgresql_include=[])
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('customer', 'admin', name='user_roles'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_users'),
    sa.UniqueConstraint('email', name='uq_users_email', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('addresses',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('addresses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('street', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_addresses_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_addresses')
    )
    op.create_table('carts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('carts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coupon_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name='fk_carts_coupon_id_coupons', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_carts_user_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_carts')
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('products_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False),
    sa.Column('meta_title', sa.VARCHAR(length=70), autoincrement=False, nullable=True),
    sa.Column('meta_description', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.Column('canonical_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name='fk_products_brand_id_brands'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_products_category_id_categories'),
    sa.PrimaryKeyConstraint('id', name='pk_products'),
    sa.UniqueConstraint('sku', name='uq_products_sku', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('slug', name='uq_products_slug', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('inventory_reservations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('inventory_reservations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_inventory_reservations_product_id_products', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_inventory_reservations_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_inventory_reservations')
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('orders_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shipping_address_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('billing_address_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('coupon_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'paid', 'processing', 'packed', 'shipped', 'delivered', 'cancelled', 'payment_failed', 'refund_pending', 'refunded', 'return_requested', 'return_approved', name='order_status'), autoincrement=False, nullable=False),
    sa.Column('order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('shipped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tracking_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('shipping_carrier', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tx_ref', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('payment_status', postgresql.ENUM('pending', 'success', 'failed', name='payment_status'), autoincrement=False, nullable=False),
    sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('tax_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('shipping_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('shipping_address_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('billing_address_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['billing_address_id'], ['addresses.id'], name='fk_orders_billing_address_id_addresses', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name='fk_orders_coupon_id_coupons', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['addresses.id'], name='fk_orders_shipping_address_id_addresses', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_orders_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_orders'),
    sa.UniqueConstraint('order_number', name='uq_orders_order_number', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('tx_ref', name='uq_orders_tx_ref', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('product_images',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('product_images_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('alt_text', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_product_images_product_id_products'),
    sa.PrimaryKeyConstraint('id', name='pk_product_images')
    )
    op.create_index('ix_product_images_id', 'product_images', ['id'], unique=False, postgresql_include=[])
    op.create_table('product_variants',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('product_variants_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attributes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_product_variants_product_id_products'),
    sa.PrimaryKeyConstraint('id', name='pk_product_variants')
    )
    op.create_index('ix_product_variants_id', 'product_variants', ['id'], unique=False, postgresql_include=[])
    op.create_index('ix_product_variants_sku', 'product_variants', ['sku'], unique=True, postgresql_include=[])
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('reviews_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_reviews_product_id_products', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_reviews_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_reviews')
    )
    op.create_table('wishlists',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('wishlists_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_wishlists_product_id_products', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_wishlists_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_wishlists'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_user_product_wishlist', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('cartitems',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('cartitems_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('variant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name='fk_cartitems_cart_id_carts', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_cartitems_product_id_products', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name='fk_cartitems_variant_id_product_variants', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_cartitems')
    )
    op.create_table('coupon_usages',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('coupon_usages_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('coupon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name='fk_coupon_usages_coupon_id_coupons', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_coupon_usages_order_id_orders', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_coupon_usages_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_coupon_usages')
    )
    op.create_index('ix_coupon_usages_id', 'coupon_usages', ['id'], unique=False, postgresql_include=[])
    op.create_table('inventory_transactions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('inventory_transactions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('quantity_change', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_before', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_after', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_inventory_transactions_created_by_users', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_inventory_transactions_order_id_orders', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_inventory_transactions_product_id_products', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_inventory_transactions')
    )
    op.create_index('ix_inventory_transactions_id', 'inventory_transactions', ['id'], unique=False, postgresql_include=[])
    op.create_table('order_events',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('order_events_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('to_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_order_events_created_by_users', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_order_events_order_id_orders', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_order_events')
    )
    op.create_table('orderitems',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('orderitems_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('variant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_orderitems_order_id_orders', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_orderitems_product_id_products', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name='fk_orderitems_variant_id_product_variants', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_orderitems')
    )
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('payments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_method', postgresql.ENUM('credit_card', 'paypal', 'bank_transfer', 'stripe', name='payment_method'), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'completed', 'failed', name='payment_transaction_status'), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('provider_payment_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('provider_event_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('refund_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('refunded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_payments_order_id_orders', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_payments')
    )
    op.create_table('return_requests',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('return_requests_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('resolution_note', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_return_requests_order_id_orders', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_return_requests_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_return_requests')
    )
    op.create_table('shipments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('shipments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tracking_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('carrier', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('shipped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('estimated_delivery', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('shipment_items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_shipments_order_id_orders', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_shipments')
    )
    op.create_index('ix_shipments_id', 'shipments', ['id'], unique=False, postgresql_include=[])
    op.create_table('payment_events',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('payment_events_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('provider_event_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_duplicate', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name='fk_payment_events_payment_id_payments', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_payment_events'),
    sa.UniqueConstraint('provider_event_id', name='uq_payment_events_provider_event_id', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )


def downgrade() -> None:
    op.drop_table('payment_events')
    op.drop_index('ix_shipments_id', table_name='shipments', postgresql_include=[])
    op.drop_table('shipments')
    op.drop_table('return_requests')
    op.drop_table('payments')
    op.drop_table('orderitems')
    op.drop_table('order_events')
    op.drop_index('ix_inventory_transactions_id', table_name='inventory_transactions', postgresql_include=[])
    op.drop_table('inventory_transactions')
    op.drop_index('ix_coupon_usages_id', table_name='coupon_usages', postgresql_include=[])
    op.drop_table('coupon_usages')
    op.drop_table('cartitems')
    op.drop_table('wishlists')
    op.drop_table('reviews')
    op.drop_index('ix_product_variants_sku', table_name='product_variants', postgresql_include=[])
    op.drop_index('ix_product_variants_id', table_name='product_variants', postgresql_include=[])
    op.drop_table('product_variants')
    op.drop_index('ix_product_images_id', table_name='product_images', postgresql_include=[])
    op.drop_table('product_images')
    op.drop_table('orders')
    op.drop_table('inventory_reservations')
    op.drop_table('products')
    op.drop_table('carts')
    op.drop_table('addresses')
    op.drop_table('users')
    op.drop_index('ix_outbox_events_topic', table_name='outbox_events', postgresql_include=[])
    op.drop_index('ix_outbox_events_status_created', table_name='outbox_events', postgresql_include=[])
    op.drop_table('outbox_events')
    op.drop_index('ix_coupons_code', table_name='coupons', postgresql_include=[])
    op.drop_table('coupons')
    op.drop_table('categories')
    op.drop_index('ix_brands_slug', table_name='brands', postgresql_include=[])
    op.drop_index('ix_brands_name', table_name='brands', postgresql_include=[])
    op.drop_index('ix_brands_id', table_name='brands', postgresql_include=[])
    op.drop_table('brands')

    # Drop the enum types created above — op.drop_table doesn't do this
    # automatically, matching the pattern already used in
    # 59ff5edac949_add_productrelation.py's downgrade().
    for enum_name in (
        'discount_types', 'outbox_status', 'user_roles', 'order_status',
        'payment_status', 'payment_method', 'payment_transaction_status',
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
