"""add_product_variant_model

Revision ID: 18017eabb055
Revises: 0a88a28a6e96
Create Date: 2026-08-25 13:24:43.563386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18017eabb055'
down_revision: Union[str, Sequence[str], None] = '0a88a28a6e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variants_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants'))
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variants_sku'), ['sku'], unique=True)

    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_cartitems_variant_id_product_variants'), 'product_variants', ['variant_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('orderitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_orderitems_variant_id_product_variants'), 'product_variants', ['variant_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitems', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orderitems_variant_id_product_variants'), type_='foreignkey')
        batch_op.drop_column('variant_id')

    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cartitems_variant_id_product_variants'), type_='foreignkey')
        batch_op.drop_column('variant_id')

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variants_sku'))
        batch_op.drop_index(batch_op.f('ix_product_variants_id'))

    op.drop_table('product_variants')
    # ### end Alembic commands ###
