"""add_product_status_and_seo

Revision ID: 2d507baa4341
Revises: bbe1fcd9935a
Create Date: 2026-08-25 13:21:14.342122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d507baa4341'
down_revision: Union[str, Sequence[str], None] = 'bbe1fcd9935a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_products')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='draft', nullable=False))
        batch_op.add_column(sa.Column('meta_title', sa.String(length=70), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('canonical_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('canonical_url')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')
        batch_op.drop_column('status')

    op.create_table('_alembic_tmp_products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.INTEGER(), nullable=False),
    sa.Column('sku', sa.VARCHAR(length=100), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('brand_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('meta_title', sa.VARCHAR(length=70), nullable=True),
    sa.Column('meta_description', sa.VARCHAR(length=160), nullable=True),
    sa.Column('canonical_url', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_products_brand_id_brands')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', name=op.f('uq_products_sku')),
    sa.UniqueConstraint('slug', name=op.f('uq_products_slug'))
    )
    # ### end Alembic commands ###
