"""Add order tracking fields

Revision ID: 3d110a8142bf
Revises: c9ce4ff3a3da
Create Date: 2026-08-24 17:12:40.058710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d110a8142bf'
down_revision: Union[str, Sequence[str], None] = 'c9ce4ff3a3da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipping_carrier', sa.String(length=100), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled', name='order_status'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled', name='order_status'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.drop_column('shipping_carrier')
        batch_op.drop_column('tracking_number')

    # ### end Alembic commands ###
