"""add_brand_model

Revision ID: bbe1fcd9935a
Revises: bede448c73d5
Create Date: 2026-08-25 13:18:58.499391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe1fcd9935a'
down_revision: Union[str, Sequence[str], None] = 'bede448c73d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands'))
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_brands_slug'), ['slug'], unique=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_products_brand_id_brands'), 'brands', ['brand_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_products_brand_id_brands'), type_='foreignkey')
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_slug'))
        batch_op.drop_index(batch_op.f('ix_brands_name'))
        batch_op.drop_index(batch_op.f('ix_brands_id'))

    op.drop_table('brands')
    # ### end Alembic commands ###
