"""Add coupons

Revision ID: c9ce4ff3a3da
Revises: 554c9035ae7c
Create Date: 2026-08-24 17:08:42.555875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ce4ff3a3da'
down_revision: Union[str, Sequence[str], None] = '554c9035ae7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_carts_coupon_id_coupons'), 'coupons', ['coupon_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_categories_name'), ['name'])
        batch_op.create_unique_constraint(batch_op.f('uq_categories_slug'), ['slug'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coupon_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_orders_order_number'), ['order_number'])
        batch_op.create_unique_constraint(batch_op.f('uq_orders_tx_ref'), ['tx_ref'])
        batch_op.create_foreign_key(batch_op.f('fk_orders_coupon_id_coupons'), 'coupons', ['coupon_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_products_sku'), ['sku'])
        batch_op.create_unique_constraint(batch_op.f('uq_products_slug'), ['slug'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_products_slug'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_products_sku'), type_='unique')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_coupon_id_coupons'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_orders_tx_ref'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_orders_order_number'), type_='unique')
        batch_op.drop_column('coupon_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_categories_slug'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_categories_name'), type_='unique')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_carts_coupon_id_coupons'), type_='foreignkey')

    # ### end Alembic commands ###
